# Formas de criar arrays numpy

In [34]:
import numpy as np

In [35]:
list = [1,2,3]

In [10]:
np.array(list)

array([1, 2, 3])

In [11]:
nested_list = [[1,2], [3,4], [5,6]]

In [12]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [13]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
# A funcao arange funciona similarmente à range tradicional do python
# Naturalmente, ela retornará um array numpy
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [17]:
# Em machine learning é comum precisar de arrays de zeros ou uns
# O numpy tem funçoes convenientes para isso
np.zeros(3)
np.ones(3)

array([1., 1., 1.])

In [19]:
# Se quisermos alterar as dimensoes do array, também podemos
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
# A funcao linspace cria um array de numeros entre x e y com um total de z breakpoints
# O retorno é  um array contendo os valores desses breakpoints
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
# Podemos criar matrizes identidade 
# Bem útil para tarefas com algebra linear
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
# A funcao random.rand retorna um array com n dimensoes 
# Números entre 0 e 1
np.random.rand(2)

array([0.26982766, 0.30296161])

In [23]:
np.random.rand(3,4)

array([[0.93641682, 0.67438914, 0.63810403, 0.51226582],
       [0.50823813, 0.01831806, 0.5908939 , 0.05588495],
       [0.79067245, 0.16485013, 0.53565789, 0.52015407]])

In [26]:
# A funcao random.randn retorna numeros entre -1 e 1
np.random.randn(3,4)

array([[ 0.19163174, -0.04953948,  1.53545956,  0.54644688],
       [ 1.10755254, -1.34119192, -0.42283159, -0.43328402],
       [-0.09522807,  1.22967445, -1.88438437, -0.04778484]])

In [29]:
# A funcao random.randint retorna numeros inteiros de x a y-1 com uma dimensao d
np.random.randint(1,100, 2)
np.random.randint(1,100, (3,3))

array([[54, 21, 53],
       [59, 74, 45],
       [36, 28, 92]])

In [32]:
# A funcao seed recebe um valor n e faz com que os valores aleatórios sempre sejam iguais
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

# Funcoes úteis para arrays numpy

In [33]:
ranarr = np.random.randint(0,50,10)

In [36]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [37]:
# Retornar o valor máximo
ranarr.max()

39

In [38]:
# Retornar o índice do valor máximo
ranarr.argmax()

7

In [39]:
# Retornar o valor mínimo
ranarr.min()

2

In [40]:
# Retornar o índice do valor máximo
ranarr.argmin()

9

In [43]:
# Recuperar o tipo de dados do array
ranarr.dtype

dtype('int64')