# Indexacao em arrays

In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# Todas as slices de array que voce pegar, sempre apontarao para o array original
arr_slice = arr[:5]

In [15]:
# Se eu fizer um broadcasting em todos os elementos dessa slice,
# mesmo que esteja em uma variiavel diferente, vai mudar no original
# A nao ser que voce faça explicitamente uma copia
arr_slice[:] = 99

In [17]:
arr_slice

array([99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [20]:
arr_copy = arr.copy()

In [22]:
# Se eu fizer o broadcast na copia e imprimir, o original estará intacto
arr_copy[:] = 100

In [23]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [24]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

# Indexacao em matrizes

In [25]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d.shape

(3, 3)

In [40]:
# Dentro dos colchetes podemos colocar os indices
# arr_2d[x][y] ou
# arr_2d[x,y]
arr_2d[0,2]

15

In [30]:
# Pouco comum, mas vale a pena saber que podemos fazer slicing multidimensionais
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

# Indexacao condicional

In [32]:
arr = np.arange(0,11)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
bool_arr = arr > 4

In [36]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [37]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [41]:
# O mais comum é fazer a expressao dentro dos colchete como no pandas
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])